//? #version 430

// These three uniforms are the parameters passed to the compute() method of your Cool::ComputeShader
//? uniform int NumberOfComputationsX;
//? uniform int NumberOfComputationsY;
//? uniform int NumberOfComputationsZ;

layout(std430, binding=0) buffer myBuffer {
   float data[];
};

// This is your main function
void cool_main() {
    uint gid = gl_GlobalInvocationID.x;
    data[gid] = data[gid] * data[gid];
}