/* -----------------------------------------------------------------------------
 * This file was automatically generated by a Python script.
 * PLEASE DON'T EDIT IT DIRECTLY, your changes would be overwritten the next time the script is run.
 * Instead, go to "style_generator.py" and edit the "style_imgui_declarations" function there.
 * -----------------------------------------------------------------------------
 */
void imgui_floating_buttons_spacing();
void imgui_frame_padding();
void imgui_tab_bar_padding();
void imgui_menu_bar_spacing();