/* -----------------------------------------------------------------------------
 * This file was automatically generated by a Python script.
 * PLEASE DON'T EDIT IT DIRECTLY, your changes would be overwritten the next time the script is run.
 * Instead, go to "style_generator.py" and edit the "style_declaration" function there.
 * -----------------------------------------------------------------------------
 */
float floating_buttons_spacing{4.f};