/* -----------------------------------------------------------------------------
 * This file was automatically generated by a Python script.
 * PLEASE DON'T EDIT IT DIRECTLY, your changes would be overwritten the next time the script is run.
 * Instead, go to "style_generator.py" and edit the "style_serialization" function there.
 * -----------------------------------------------------------------------------
 */
cereal::make_nvp("Floating buttons spacing", floating_buttons_spacing)